# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Eden Rabbie
description: "Product manager in UAE"
keywords: "product management, startups, business strategy, data science"
url: http://edenrabbie.github.io
baseurl: "/end2end"

google_analytics: 
repo: http://github.com/edenrabbie/end2end
disqus_shortname: 
disqus_site_shortname: 

# Author settings
author:
  name: Eden Rabbie
  job: Product Manager
  bio: "At the intersection of startups and product management, to create value and outsmart doubt."
  thumb: /photo.jpg
  email: eden@edenrabbie.com
  url: https://edenrabbie.com/
  #github: https://github.com/nandomoreirame
  twitter: https://twitter.com/edenrabbie
  #facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/edenrabbie
  medium: https://medium.com/@edenrabbie

# navbar pages
#navbar:

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
